
import java.io.*;

public class TestClass
{


    //=====================================================
    public static void main(String[] args)
    {

    new Calculator("LOG00003.txt");
                                                                //enter raw file name here

    readAndWriteOrderedPair();
                                                                //used to test read OrderedPairs from
                                                                //.dat files generated by Calculator
                                                                //and create a results.txt file for
                                                                //easy visualization.
                                                                //(results.txt is comma separated)

    }
    //=====================================================
    private static void readAndWriteOrderedPair()
    {

    OrderedPair op;
    FileInputStream fis;
    FileOutputStream fos;
    ObjectInputStream ois;
    PrintWriter pr;

    try
        {

        fis = new FileInputStream("LOG00003_MPU9250_TxD_z.dat");
                                                                //just place the name of the .dat file you want to
                                                                //read an OrderedPair from here.

        fos = new FileOutputStream("results.txt");

        ois = new ObjectInputStream(fis);
        pr = new PrintWriter(fos);

        for (int i=0; i < 3070; i++)
            {
            op = new OrderedPair();

            op.readOrderedPair(ois);

            System.out.println("xValue: " + op.xValue + "    yValue: " + op.yValue);

            pr.print(op.xValue);
            pr.print(",");
            pr.print(op.yValue);
            pr.print("\n");
            }

        pr.flush();

        }
    catch (IOException ioe)
        {
        ioe.printStackTrace();
        }

    }
    //=====================================================


}