
import java.io.*;

public class TestClass
{

    //=====================================================
    public static void main(String[] args)
    {

    String rawFileName;
    String dataFileName_x;
    String dataFileName_y;
    String dataFileName_z;
    String outputFileName_x;
    String outputFileName_y;
    String outputFileName_z;
    int numberOfLinesInRawFile;
    int numberOfLinesAveraged;
    double noiseThreshold;


    rawFileName = new String("test.txt");

    dataFileName_x = new String("test_MPU9250_TxA_x.dat");
    dataFileName_y = new String("test_MPU9250_TxA_y.dat");
    dataFileName_z = new String("test_MPU9250_TxA_z.dat");

    outputFileName_x = new String("results_x.csv");
    outputFileName_y = new String("results_y.csv");
    outputFileName_z = new String("results_z.csv");

    numberOfLinesInRawFile = 40;

    numberOfLinesAveraged = 5;

    noiseThreshold = 0.01;


    new Calculator(rawFileName, numberOfLinesAveraged, noiseThreshold);


    readAndWriteOrderedPair(dataFileName_x,
                            dataFileName_y,
                            dataFileName_z,
                            outputFileName_x,
                            outputFileName_y,
                            outputFileName_z,
                            numberOfLinesInRawFile);
                                                                //used to test read OrderedPairs from
                                                                //.dat files generated by Calculator
                                                                //and create a results.csv file for
                                                                //easy visualization.

    }
    //=====================================================
    private static void readAndWriteOrderedPair(String dataFileName_x,
                                                String dataFileName_y,
                                                String dataFileName_z,
                                                String outputFileName_x,
                                                String outputFileName_y,
                                                String outputFileName_z,
                                                int numberOfLinesInRawFile)
    {

    OrderedPair op;
    FileInputStream fis;
    FileOutputStream fos;
    ObjectInputStream ois;
    PrintWriter pr;

    try
        {

        fis = new FileInputStream(dataFileName_x);

        fos = new FileOutputStream(outputFileName_x);

        ois = new ObjectInputStream(fis);
        pr = new PrintWriter(fos);

        for (int i=0; i < numberOfLinesInRawFile; i++)
            {
            op = new OrderedPair();

            op.readOrderedPair(ois);

            //System.out.println("xValue: " + op.xValue + "    yValue: " + op.yValue);

            pr.print(op.xValue);
            pr.print(",");
            pr.print(op.yValue);
            pr.print("\n");
            }

        pr.flush();

        fis = new FileInputStream(dataFileName_y);

        fos = new FileOutputStream(outputFileName_y);

        ois = new ObjectInputStream(fis);
        pr = new PrintWriter(fos);

        for (int i=0; i < numberOfLinesInRawFile; i++)
            {
            op = new OrderedPair();

            op.readOrderedPair(ois);

            //System.out.println("xValue: " + op.xValue + "    yValue: " + op.yValue);

            pr.print(op.xValue);
            pr.print(",");
            pr.print(op.yValue);
            pr.print("\n");
            }

        pr.flush();

        fis = new FileInputStream(dataFileName_z);

        fos = new FileOutputStream(outputFileName_z);

        ois = new ObjectInputStream(fis);
        pr = new PrintWriter(fos);

        for (int i=0; i < numberOfLinesInRawFile; i++)
            {
            op = new OrderedPair();

            op.readOrderedPair(ois);

            //System.out.println("xValue: " + op.xValue + "    yValue: " + op.yValue);

            pr.print(op.xValue);
            pr.print(",");
            pr.print(op.yValue);
            pr.print("\n");
            }

        pr.flush();

        }
    catch (IOException ioe)
        {
        ioe.printStackTrace();
        }

    }
    //=====================================================


}