/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

public class FlightPanel extends javax.swing.JPanel
{

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form FlightPanel
     */
    public FlightPanel()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        velocitySplitPlane = new javax.swing.JSplitPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AccelerationSplitPane = new javax.swing.JSplitPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        gyroscopeSplitPane = new javax.swing.JSplitPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("Options go here");
        velocitySplitPlane.setLeftComponent(jLabel3);

        jLabel4.setText("Velocity Graph goes here");
        velocitySplitPlane.setRightComponent(jLabel4);

        jTabbedPane1.addTab("Velocity", velocitySplitPlane);

        jLabel5.setText("Options go here");
        AccelerationSplitPane.setLeftComponent(jLabel5);

        jLabel6.setText("Acceleration graph goes here");
        AccelerationSplitPane.setRightComponent(jLabel6);

        jTabbedPane1.addTab("Acceleration", AccelerationSplitPane);

        jLabel1.setText("OPTIONS HERE");
        gyroscopeSplitPane.setLeftComponent(jLabel1);

        jLabel2.setText("GYROSCOPE GRAPH GOES HERE");
        gyroscopeSplitPane.setRightComponent(jLabel2);

        jTabbedPane1.addTab("GyroScope", gyroscopeSplitPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane AccelerationSplitPane;
    private javax.swing.JSplitPane gyroscopeSplitPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSplitPane velocitySplitPlane;
    // End of variables declaration//GEN-END:variables
}
