package userinterface;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

public class rsc_jframe extends javax.swing.JFrame
{

    private static final long serialVersionUID = 1L;
    private java.io.File rawFlightfile;
    private java.io.File flightFile;
    private javax.swing.JFileChooser tempFileChooser;

    /**
     * Creates new form rsc_jframe
     */
    public rsc_jframe()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        rscJTabbedPane = new javax.swing.JTabbedPane();
        welcomePanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        rscJMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loadRawMenuItem = new javax.swing.JMenuItem();
        loadFlightMenutItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        testMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" RockSat-C");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.color1"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setName("Welcome"); // NOI18N

        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/WelcomeScreen.jpg"))); // NOI18N
        welcomeLabel.setToolTipText("");

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1287, Short.MAX_VALUE)
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
        );

        rscJTabbedPane.addTab("Welcome Tab", welcomePanel);

        rscJMenuBar.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.color2"));
        rscJMenuBar.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.color1"));
        rscJMenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        fileMenu.setText("File");

        loadRawMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        loadRawMenuItem.setText("New Flight (load Raw)");
        loadRawMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                loadRawMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(loadRawMenuItem);

        loadFlightMenutItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        loadFlightMenutItem.setText("Open Flight");
        loadFlightMenutItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                loadFlightMenutItemActionPerformed(evt);
            }
        });
        fileMenu.add(loadFlightMenutItem);

        rscJMenuBar.add(fileMenu);

        editMenu.setText("Edit");

        testMenuItem.setText("LOADTestFlight");
        testMenuItem.setEnabled(false);
        testMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                testMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(testMenuItem);

        rscJMenuBar.add(editMenu);

        setJMenuBar(rscJMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1289, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(rscJTabbedPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 819, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(rscJTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadRawMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_loadRawMenuItemActionPerformed
    {//GEN-HEADEREND:event_loadRawMenuItemActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                rawFlightfile = new java.io.File(".");
                tempFileChooser = new javax.swing.JFileChooser(rawFlightfile);
                FileNameExtensionFilter tempFileNameExtensionFilter = new FileNameExtensionFilter("Raw Flight Format (txt, or csv)", "csv", "txt");
                tempFileChooser.addChoosableFileFilter(tempFileNameExtensionFilter);
                tempFileChooser.setFileFilter(tempFileNameExtensionFilter);
                int returnVal = tempFileChooser.showOpenDialog(rsc_jframe.this);
                if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION)
                {
                    rawFlightfile = tempFileChooser.getSelectedFile();
                    JOptionPane.showMessageDialog(null, "File selected:" + rawFlightfile.getName());
                    rscJTabbedPane.addTab(rawFlightfile.getName(), null, new FlightPanel(rawFlightfile, FlightPanel.LOAD_RAW));
                }
            }
        });
    }//GEN-LAST:event_loadRawMenuItemActionPerformed

    private void loadFlightMenutItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_loadFlightMenutItemActionPerformed
    {//GEN-HEADEREND:event_loadFlightMenutItemActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                flightFile = new java.io.File(".");
                tempFileChooser = new javax.swing.JFileChooser(flightFile);
                tempFileChooser.setMultiSelectionEnabled(false);
                FileNameExtensionFilter tempFileNameExtensionFilter = new FileNameExtensionFilter("Flight File Format (rsc)", "rsc");
                tempFileChooser.addChoosableFileFilter(tempFileNameExtensionFilter);
                tempFileChooser.setFileFilter(tempFileNameExtensionFilter);
                int returnVal = tempFileChooser.showOpenDialog(rsc_jframe.this);
                if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION)
                {
                    flightFile = tempFileChooser.getSelectedFile();
                    JOptionPane.showMessageDialog(null, "File selected: " + flightFile.getName());
                    rscJTabbedPane.addTab(flightFile.getName(), null, new FlightPanel(flightFile, FlightPanel.LOAD_FLIGHT));
                }
            }
        });
    }//GEN-LAST:event_loadFlightMenutItemActionPerformed

    private void testMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testMenuItemActionPerformed
    {//GEN-HEADEREND:event_testMenuItemActionPerformed
        rscJTabbedPane.addTab("Test Flight", null, new FlightPanel());
    }//GEN-LAST:event_testMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        try
        {
            // imported from https://github.com/bulenkov/Darcula, to compile this you will need to include it as a library. (note to run the JAR it will need to be near by as well)
            javax.swing.plaf.basic.BasicLookAndFeel darcula = new com.bulenkov.darcula.DarculaLaf();
            javax.swing.UIManager.setLookAndFeel(darcula);

            /*// old leftover incase we dont want to use this imported theme.
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
                //Set the Nimbus look and feel
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                // If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                // For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            }*/
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(rsc_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (Exception e)
        {
            java.util.logging.Logger.getLogger(rsc_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new rsc_jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem loadFlightMenutItem;
    private javax.swing.JMenuItem loadRawMenuItem;
    private javax.swing.JMenuBar rscJMenuBar;
    private javax.swing.JTabbedPane rscJTabbedPane;
    private javax.swing.JMenuItem testMenuItem;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
