package userinterface;

import java.io.*;

public
        class TestClass
{

    //=====================================================
    public static
            void main(String[] args)
    {

        //new Calculator("atRest.txt");
        //enter raw file name here
        //readOrderedPair();
        //used to test read OrderedPairs from
        //.dat files generated by Calculator
    }

    //=====================================================
    private static
            void readOrderedPair()
    {

        OrderedPair op;
        FileInputStream fis;
        ObjectInputStream ois;

        try
        {

            fis = new FileInputStream("atRest_MPU9250_TxD_z.dat");
            //just place the name of the .dat file you want to
            //read an OrderedPair from here.
            ois = new ObjectInputStream(fis);

            for (int i = 0; i < 250; i++)
            {
                op = new OrderedPair();

                op.readOrderedPair(ois);

                System.out.println("xValue: " + op.xValue + "    yValue: " + op.yValue);
            }

        }
        catch (IOException ioe)
        {
            ioe.printStackTrace();
        }

    }
    //=====================================================

}
